### ISSUE TITLE
Controllers with re-namespace cannot work

### ISSUE THREAD

**Issue by dungnh** [stefanzweifel/laravel-stats#114]
Hi, I just tried to use this package but I got this issue:

```
In Container.php line 752:
Class App\Http\Controllers\Auth\LoginController does not exist
```

As in my app Controllers, I've put namespace as \App\Controllers\Frontend  & \App\Controllers\Backend (follow structure from [Laravel-Boilerplate](https://github.com/rappasoft/laravel-5-boilerplate)  ).
Could you please help about this issue?

**Comment by stefanzweifel** [comment]
Hi

I think the issue is not in laravel-stats, but in the structure of your controllers. When I understand your issue correctly, you've started a project with laravel-5-boilerplate and have run `php artisan auth:make` (?) to generate the `LoginController`. Then when you try to run `php artisan stats` the error occurs.

Or how is the LoginController generated? Because the boilerplate project already comes with a [LoginController](https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Http/Controllers/Frontend/Auth/LoginController.php).

For me it seems, that the LoginController is in the wrong folder, has the wrong namespace or composer somehow doesn't see your LoginController. Could you also run `composer dumpautoload` and try it again?

**Comment by dungnh** [comment]
Hi, thank you for answering me. 
Yes, I did create Auth by artisan before, but I did move it and change namespace. So now, in controllers, it will come with Frontend\Auth.
That's running project and I want to stats our code. I did composer dump-autoload but still not luck. How do you think?

**Comment by stefanzweifel** [comment]
Are you using `Auth::routes()` in your `routes/web.php` file?
I think that helper-method just assumes that the LoginController is placed in `App\Http\Controllers\Auth\LoginController` and **not** in `App\Http\Controllers\Frontend\Auth\LoginController`.

I saw that the laravel-boilerplate project also [explicitly writes it's own routes](https://github.com/rappasoft/laravel-5-boilerplate/blob/master/routes/frontend/auth.php) for the LoginController.
Maybe you have to decide which Boilerplate code you want to keep: The one from `php artisan auth:make` or the one from the boilerplate-project.

When running `php artisan stats` the laravel-stats packages is starting Laravel's internal router tries to load all conrollers. I think that's why the error occurs.
I assume when you're running `php artisan routes:list` you will see the same error message.

**Comment by dungnh** [comment]
Hi again, thank you for your help. 
I tried to run `php artisan route:list` and fixed it. Now,  the  `php artisan stats` can work well.
