### ISSUE TITLE
can't support my laravel 5.4 project

### ISSUE THREAD

**Issue by gathuku** [stefanzweifel/laravel-stats#146]

**Comment by stefanzweifel** [comment]
Hi

The package uses some features of Laravel which are not available in Laravel 5.4. When I first released the package Laravel 5.5 was the most recent version (it's also a LTS version) so I stuck to that.

I can only suggest to update your Laravel application to a newer version (or even better, to the latest version). 
Laravel 5.4 also doesn't receive security fixes since January 2018 (See [Laravel's support policy](https://laravel.com/docs/5.8/releases#support-policy)).
