### ISSUE TITLE
Not installing in Laravel 7

### ISSUE THREAD

**Issue by devfaysal** [stefanzweifel/laravel-stats#171]
Problem 1
    - Conclusion: don't install wnx/laravel-stats v2.1.1
    - Conclusion: don't install wnx/laravel-stats v2.1.0|remove sebastian/version 2.0.1
    - Conclusion: don't install wnx/laravel-stats v2.1.0|don't install sebastian/version 2.0.1
    - Installation request for wnx/laravel-stats ^2.1 -> satisfiable by wnx/laravel-stats[v2.1.0, v2.1.1].
    - wnx/laravel-stats v2.1.0 requires phploc/phploc ~6.0 -> satisfiable by phploc/phploc[6.0.0, 6.0.1, 6.0.2, 6.0.x-dev].
    - phploc/phploc 6.0.0 requires sebastian/version ^3.0 -> satisfiable by sebastian/version[3.0.0, 3.0.x-dev].
    - phploc/phploc 6.0.1 requires sebastian/version ^3.0 -> satisfiable by sebastian/version[3.0.0, 3.0.x-dev].
    - phploc/phploc 6.0.2 requires sebastian/version ^3.0 -> satisfiable by sebastian/version[3.0.0, 3.0.x-dev].
    - phploc/phploc 6.0.x-dev requires sebastian/version ^3.0 -> satisfiable by sebastian/version[3.0.0, 3.0.x-dev].
    - Can only install one of: sebastian/version[3.0.0, 2.0.1].
    - Can only install one of: sebastian/version[3.0.x-dev, 2.0.1].
    - Installation request for sebastian/version (locked at 2.0.1) -> satisfiable by sebastian/version[2.0.1].

**Comment by stefanzweifel** [comment]
Hi, 

This problem is related to the incompatibility of stats with when phpunit 8 is installed. We've dropped support for phpunit 8 in [the latest release](https://github.com/stefanzweifel/laravel-stats/releases/tag/v2.1.1).

I know it's not perfect, but it was the easiest route to get a Laravel 7 compatible version out of the door.

I will update the README to make clear, that the package requires phpunit 9.
