### ISSUE TITLE
Is laravel 5.5 absolutely required?

### ISSUE THREAD

**Issue by michaeljhopkins** [stefanzweifel/laravel-stats#23]
Thought this was rad and would like to use it in my laravel app, but I am not yet at 5.5. Are you using features that only exist in 5.5 or can this be 5.*?

**Comment by mfour-merickson** [comment]
I am wondering the same thing.  I was planning to add to a legacy 5.1 project, but the minimum version for Laravel is 5.5 (as stated above)

**Comment by mikeerickson** [comment]
I have forked the repo and am going to see if it can work with earlier versions of Laravel.  I am going to attempt to go back to 5.1

@michaeljhopkins What version of Laravel are you needing to support?

**Comment by stefanzweifel** [comment]
I think adding support for Laravel Versions below 5.5 shouldn't be too hard.

You would have to adjust the version numbers for illuminate/support in composer. json.

Happy to see a PR for this

**Comment by stefanzweifel** [comment]
The only problem I see is that testing the package for multiple Laravel version could get complicated.

**Comment by thecrypticace** [comment]
I'd be happy to help set up Travis to test against multiple Laravel versions when you get to that point. I've done this with multiple PHPUnit versions in the past.

**Comment by stefanzweifel** [comment]
The package will only support Laravel 5.5 and higher. 

#70 would have been the PR to introduce backwards compatibility. Anyone can read through the changes and probably agree that it would make everything much more complicated and harder to maintain.
When new Laravel Versions are released the package will always work with previous releases and security bugs will be fixed.

I will update the docs accordingly so that everyone discovering the package knows the state to this question.
